---

- name: Install Plex Media Server
  ansible.builtin.command: "qpkg_cli --keep --manually {{ plex_download.dest }}"
  register: install_result
  become: true
  changed_when: true

- name: Show Plex Media Server install result
  ansible.builtin.debug:
    msg: "{{ install_result.stdout_lines }}"

- name: Wait for installation
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      qpkg_cli --list | grep '\[PlexMediaServer\]'
    executable: /bin/bash
  register: list_result
  failed_when: false
  until: "list_result.rc > 0"
  retries: 10
  delay: 20
  changed_when: true

- name: Confirm Plex Media Server installed
  ansible.builtin.debug:
    msg: "Plex was installed"
